sudo: required
services:
  - docker

before_install:
  - docker build -t martinshell/react-test -f ./client/Dockerfile.dev ./client

script:
  -  - docker run -e CI=true martinshell/react-test npm test

after_success:
  - docker build -t martinshell/multi-client ./client
  - docker build -t martinshell/multi-nginx ./nginx
  - docker build -t martinshell/multi-server ./server
  - docker build -t martinshell/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push martinshell/multi-client
  - docker push martinshell/multi-nginx
  - docker push martinshell/multi-server
  - docker push martinshell/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: 	elasticbeanstalk-us-east-1-300706864044
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
